### ISSUE TITLE
мавен билд не работает

### ISSUE THREAD

**Issue by Ruskiz** [ZaerkoDV/InstinctoolsProgects#1]
ни билд ни компиляция ни тесты не запускаются через мавен, проверь плиз до встречи, потому что я не смог локально поднять твое приложение.

**Comment by ZaerkoDV** [comment]
ок проверю (закомичу снова последнюю версию) хотя у меня все норм. Вот
бд(забыл прикрепить).

15 июля 2015 г., 16:20 пользователь Ruskiz notifications@github.com
написал:

> ни билд ни компиляция ни тесты не запускаются через мавен, проверь плиз до
> встречи, потому что я не смог локально поднять твое приложение.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1.

## 

_Best Regards,_
- Denis Zaerko*

_skype: zaerko.denis_
_Mob: +375298688744_

**Comment by Ruskiz** [comment]
А ты попробуй забрать по чистому, в новую дирректорию, и только мавеном из
консоли, собрать проект и запустить тесты

15 июля 2015 г., 16:34 пользователь ZaerkoDV notifications@github.com
написал:

**Comment by ZaerkoDV** [comment]
Да, версия на github не собиралась. Я добавил еще одну зависимость и все
стало собираться хотя есть ошибки(скрины).

15 июля 2015 г., 16:36 пользователь Ruskiz notifications@github.com
написал:

> А ты попробуй забрать по чистому, в новую дирректорию, и только мавеном из
> консоли, собрать проект и запустить тесты
> 
> 15 июля 2015 г., 16:34 пользователь ZaerkoDV notifications@github.com
> написал:
> 
> > ок проверю (закомичу снова последнюю версию) хотя у меня все норм. Вот
> > бд(забыл прикрепить).
> > 
> > 15 июля 2015 г., 16:20 пользователь Ruskiz notifications@github.com
> > написал:
> > 
> > > ни билд ни компиляция ни тесты не запускаются через мавен, проверь
> > > плиз
> > > до
> > > встречи, потому что я не смог локально поднять твое приложение.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1.
> > 
> > ## 
> > 
> > _Best Regards,_
> > - Denis Zaerko*
> > 
> > _skype: zaerko.denis_
> > _Mob: +375298688744_
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1#issuecomment-121618811>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1#issuecomment-121619472
> .

## 

_Best Regards,_
- Denis Zaerko*

_skype: zaerko.denis_
_Mob: +375298688744_

**Comment by Ruskiz** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project ReducerLinks: Compilation failure: Compilation failure:
[ERROR] /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[13,21] error: package javaQuery.j2ee does not exist
[ERROR] /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[98,2] error: cannot find symbol
[ERROR] symbol:   class tinyURL
[ERROR] location: class LinkService
[ERROR] /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[98,19] error: cannot find symbol
[ERROR] symbol:   class tinyURL
[ERROR] location: class LinkService
[ERROR] /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[129,2] error: cannot find symbol
[ERROR] symbol:   class tinyURL
[ERROR] location: class LinkService
[ERROR] /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[129,19] error: cannot find symbol
[ERROR] -> [Help 1]

забрал твой последний код, вижу что ничего не изменилось, зачем отписывал что подправил?

**Comment by ZaerkoDV** [comment]
А я наверное javaQuery jar отдельно подключал не указывал в пом. Наверное
из за этого несобирается . У меня была библиотка локально ((( . Наверное из
за этого. Если можно я сейчас опять комитить не буду(чтобы были осмысленные
комиты) .Завтра решу проблему дублирования первичного ключа и сразу добавлю
депенденси с этой библиотекой. Или сейчас заливать. Спасибо.

четверг, 16 июля 2015 г. пользователь Ruskiz написал:

> [ERROR] Failed to execute goal
> org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile
> (default-compile) on project ReducerLinks: Compilation failure: Compilation
> failure:
> [ERROR]
> /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[13,21]
> error: package javaQuery.j2ee does not exist
> [ERROR]
> /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[98,2]
> error: cannot find symbol
> [ERROR] symbol: class tinyURL
> [ERROR] location: class LinkService
> [ERROR]
> /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[98,19]
> error: cannot find symbol
> [ERROR] symbol: class tinyURL
> [ERROR] location: class LinkService
> [ERROR]
> /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[129,2]
> error: cannot find symbol
> [ERROR] symbol: class tinyURL
> [ERROR] location: class LinkService
> [ERROR]
> /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[129,19]
> error: cannot find symbol
> [ERROR] -> [Help 1]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1#issuecomment-121849643
> .

## 

_Best Regards,_
- Denis Zaerko*

_skype: zaerko.denis_
_Mob: +375298688744_

**Comment by Ruskiz** [comment]
доведи до ума, потом маякни

16.07.15, ZaerkoDVnotifications@github.com написал(а):

**Comment by ZaerkoDV** [comment]
Добрый день сори что беспокою. Я писал Ирине но она не отписала(может в
отпуске) и я решил написать вам. Не знаю по адресу или нет(сори если зря
побеспокоил).
Вы сказали попробовать другие варианты (проблема дубликата ключей и как
следствие отсутствие записей в бд т.е. их сохранение). Я пробовал другие
варианты но это не помогает(вернулся к тому что было). Я правда не понимаю
в чем проблема. С MySQL все работает норм а с postgesql нет. Я не пробовал
вариант с указанием другого типа не columnDefinition="integer" а тот
который вы предлагали(если не сложно как название этого типа) и не пробjвал
писать запросы через Criteria (попробую но врятли что то измениться).Есть
еще вопросы с ангуляром(но их не задам так так). Подскажите что дальше (я
не уверен что смогу найти ошибку т.к. перепробовал вар и они не подошли).
Еще раз извините что побеспокоил. Спасибо.

https://github.com/ZaerkoDV/InstinctoolsProgects

Я исправил тесты(сделал их независимыми CRUD) и положил в директорию
javaQuery.jar

16 июля 2015 г., 10:25 пользователь Ruskiz notifications@github.com
написал:

> доведи до ума, потом маякни
> 
> 16.07.15, ZaerkoDVnotifications@github.com написал(а):
> 
> > А я наверное javaQuery jar отдельно подключал не указывал в пом.
> > Наверное
> > из за этого несобирается . У меня была библиотка локально ((( . Наверное
> > из
> > за этого. Если можно я сейчас опять комитить не буду(чтобы были
> > осмысленные
> > комиты) .Завтра решу проблему дублирования первичного ключа и сразу
> > добавлю
> > депенденси с этой библиотекой. Или сейчас заливать. Спасибо.
> > 
> > четверг, 16 июля 2015 г. пользователь Ruskiz написал:
> > 
> > > [ERROR] Failed to execute goal
> > > org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile
> > > (default-compile) on project ReducerLinks: Compilation failure:
> > > Compilation
> > > failure:
> > > [ERROR]
> > > 
> > > /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[13,21]
> > > 
> > > error: package javaQuery.j2ee does not exist
> > > [ERROR]
> > > 
> > > /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[98,2]
> > > 
> > > error: cannot find symbol
> > > [ERROR] symbol: class tinyURL
> > > [ERROR] location: class LinkService
> > > [ERROR]
> > > 
> > > /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[98,19]
> > > 
> > > error: cannot find symbol
> > > [ERROR] symbol: class tinyURL
> > > [ERROR] location: class LinkService
> > > [ERROR]
> > > 
> > > /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[129,2]
> > > 
> > > error: cannot find symbol
> > > [ERROR] symbol: class tinyURL
> > > [ERROR] location: class LinkService
> > > [ERROR]
> > > 
> > > /home/ruskiz/projects/internal/interview/zaerko/ReducerLinks/src/main/java/com/zaerko/reducerlinks/service/LinkService.java:[129,19]
> > > 
> > > error: cannot find symbol
> > > [ERROR] -> [Help 1]
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1#issuecomment-121849643>
> > > 
> > > .
> > 
> > ## 
> > 
> > _Best Regards,_
> > - Denis Zaerko*
> > 
> > _skype: zaerko.denis_
> > _Mob: +375298688744_
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1#issuecomment-121855513
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ZaerkoDV/InstinctoolsProgects/issues/1#issuecomment-121858002
> .

## 

_Best Regards,_
- Denis Zaerko*

_skype: zaerko.denis_
_Mob: +375298688744_
